version: "3.7"

services:
  exercise1:
    image: exercise1
    ports:
      - "8080:80"
    networks:
      - frontend
    deploy:
      replicas: 1
  exercise2:
    image: exercise2
    ports:
      - "8081:80"
    networks:
      - frontend
    deploy:
      replicas: 1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

networks:
  frontend:
